### ISSUE TITLE
Usar Logo Nick Games como Favicon

### ISSUE THREAD

**Issue by raphael-foliveira** [nicklima-amigos/EntregaFinalA3#57]
Abrindo essa issue só pra que a gente lembre de trocar o Favicon no front pra a logo Nick Games

**Comment by nicolas-limadev** [comment]
Der uma ideia de logo.

**Comment by raphael-foliveira** [comment]
> Der uma ideia de logo.

Podemos usar a que está na tela de Login hoje. Alguém se opõe?

**Comment by nicolas-limadev** [comment]
Sim, pensei em uma ideia de uma caricatura em formato de desenho.

**Comment by manoelduran** [comment]
temos que mudar a logo, colocar uma caricatura em formato de desenho

**Comment by nicolas-limadev** [comment]
Eu irei realizar hoje a logo no Photoshop, se quiserem acompanhar no discord estarei lá.

**Comment by raphael-foliveira** [comment]
A logo foi feita e implementada no código? Se sim, podemos fechar essa issue. Seria interessante mencionar o PR que resolveu isso por aqui também.
