### ISSUE TITLE
Paleta de cores da plataforma

### ISSUE THREAD

**Issue by manoelduran** [nicklima-amigos/EntregaFinalA3#67]
Estou abrindo essa issue, para definirmos as paleta de cores que iremos usar na plataforma, eu coloquei o amarelo e o laranja apenas para fazer e ter algo visual, mas essa parte ainda não está definida do projeto. O que vocês acham? Mantem as cores? Altera? Sugestões please

**Comment by nicolas-limadev** [comment]
Bom dia, 

Cor Principal: Verde Floresta (#228B22)
Cor Secundária: Cinza Escuro (#333333)
Cor de Destaque: Roxo Profundo (#800080)
Cor de Fundo: Marrom Escuro (#2E1E0B)
Cor de Texto: Branco Antigo (#FDFEFE)

**Comment by raphael-foliveira** [comment]
Gostei da idéia de paleta de @nicolas-limadev

**Comment by manoelduran** [comment]
Também gostei! @Helio-Jr  alguma sugestão?

**Comment by Helio-Jr** [comment]
Gosto da sugestão de Nick! Uma outra ideia que tive seria fazer algo numa estética futurista, utilizando fundo preto e ter como cor principal o verde. Semelhante ao seguinte site: https://ada.tech/

**Comment by manoelduran** [comment]
> Gosto da sugestão de Nick! Uma outra ideia que tive seria fazer algo numa estética futurista, utilizando fundo preto e ter como cor principal o verde. Semelhante ao seguinte site: https://ada.tech/

acho que seriam essas cores: [15:52, 13/10/2023] Manoel Duran: background-color: rgb(24, 28, 35);
[15:52, 13/10/2023] Manoel Duran: color: rgb(166, 247, 80);
[15:53, 13/10/2023] Manoel Duran: color: rgb(255, 251, 240);

**Comment by manoelduran** [comment]
Então vamos usar a paleta que está no protótipo?

**Comment by raphael-foliveira** [comment]
Exato. Acho que está satisfatório
